/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : string,
}
export interface AttendanceRecord {
  'studentId' : bigint,
  'present' : boolean,
  'date' : string,
}
export interface Class { 'id' : bigint, 'name' : string }
export interface ClassAssignment { 'section' : string, 'classId' : bigint }
export interface Student {
  'id' : bigint,
  'name' : string,
  'section' : string,
  'classId' : bigint,
}
export interface Subject { 'id' : bigint, 'name' : string, 'classId' : bigint }
export interface Teacher {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'periodEnd' : string,
  'classAssignments' : Array<ClassAssignment>,
  'periodStart' : string,
}
export interface _SERVICE {
  'createAnnouncement' : ActorMethod<[string, string, string], Announcement>,
  'createClass' : ActorMethod<[string], Class>,
  'createStudent' : ActorMethod<[string, bigint, string], Student>,
  'createSubject' : ActorMethod<[string, bigint], Subject>,
  'createTeacher' : ActorMethod<
    [string, string, Array<ClassAssignment>, string, string],
    Teacher
  >,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteClass' : ActorMethod<[bigint], undefined>,
  'deleteStudent' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'deleteTeacher' : ActorMethod<[bigint], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllClasses' : ActorMethod<[], Array<Class>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getAllTeachers' : ActorMethod<[], Array<Teacher>>,
  'getAnnouncement' : ActorMethod<[bigint], [] | [Announcement]>,
  'getAttendanceRecords' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getClass' : ActorMethod<[bigint], [] | [Class]>,
  'getStudent' : ActorMethod<[bigint], [] | [Student]>,
  'getStudentsByClass' : ActorMethod<[bigint], Array<Student>>,
  'getSubject' : ActorMethod<[bigint], [] | [Subject]>,
  'getSubjectsByClass' : ActorMethod<[bigint], Array<Subject>>,
  'getTeacher' : ActorMethod<[bigint], [] | [Teacher]>,
  'markAttendance' : ActorMethod<[bigint, string, boolean], undefined>,
  'updateAnnouncement' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
  'updateClass' : ActorMethod<[bigint, string], undefined>,
  'updateStudent' : ActorMethod<[bigint, string, bigint, string], undefined>,
  'updateSubject' : ActorMethod<[bigint, string, bigint], undefined>,
  'updateTeacher' : ActorMethod<
    [bigint, string, string, Array<ClassAssignment>, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];