/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
});
export const Class = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'classId' : IDL.Nat,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'classId' : IDL.Nat,
});
export const ClassAssignment = IDL.Record({
  'section' : IDL.Text,
  'classId' : IDL.Nat,
});
export const Teacher = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'periodEnd' : IDL.Text,
  'classAssignments' : IDL.Vec(ClassAssignment),
  'periodStart' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'studentId' : IDL.Nat,
  'present' : IDL.Bool,
  'date' : IDL.Text,
});

export const idlService = IDL.Service({
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Announcement],
      [],
    ),
  'createClass' : IDL.Func([IDL.Text], [Class], []),
  'createStudent' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Student], []),
  'createSubject' : IDL.Func([IDL.Text, IDL.Nat], [Subject], []),
  'createTeacher' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(ClassAssignment), IDL.Text, IDL.Text],
      [Teacher],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteClass' : IDL.Func([IDL.Nat], [], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'deleteTeacher' : IDL.Func([IDL.Nat], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Nat], [IDL.Opt(Announcement)], ['query']),
  'getAttendanceRecords' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(Class)], ['query']),
  'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getStudentsByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
  'getSubject' : IDL.Func([IDL.Nat], [IDL.Opt(Subject)], ['query']),
  'getSubjectsByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Subject)], ['query']),
  'getTeacher' : IDL.Func([IDL.Nat], [IDL.Opt(Teacher)], ['query']),
  'markAttendance' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
  'updateAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateClass' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateStudent' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'updateTeacher' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ClassAssignment),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
  });
  const Class = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'classId' : IDL.Nat,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'classId' : IDL.Nat,
  });
  const ClassAssignment = IDL.Record({
    'section' : IDL.Text,
    'classId' : IDL.Nat,
  });
  const Teacher = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'periodEnd' : IDL.Text,
    'classAssignments' : IDL.Vec(ClassAssignment),
    'periodStart' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'studentId' : IDL.Nat,
    'present' : IDL.Bool,
    'date' : IDL.Text,
  });
  
  return IDL.Service({
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Announcement],
        [],
      ),
    'createClass' : IDL.Func([IDL.Text], [Class], []),
    'createStudent' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Student], []),
    'createSubject' : IDL.Func([IDL.Text, IDL.Nat], [Subject], []),
    'createTeacher' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(ClassAssignment), IDL.Text, IDL.Text],
        [Teacher],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteClass' : IDL.Func([IDL.Nat], [], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'deleteTeacher' : IDL.Func([IDL.Nat], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Nat], [IDL.Opt(Announcement)], ['query']),
    'getAttendanceRecords' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(Class)], ['query']),
    'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getStudentsByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
    'getSubject' : IDL.Func([IDL.Nat], [IDL.Opt(Subject)], ['query']),
    'getSubjectsByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Subject)], ['query']),
    'getTeacher' : IDL.Func([IDL.Nat], [IDL.Opt(Teacher)], ['query']),
    'markAttendance' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
    'updateAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateClass' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateStudent' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'updateTeacher' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ClassAssignment),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };